version: '3.7'
services:
  marst-service:
    build:
      context: docker
      target: marst
    restart: on-failure
    volumes:
      - ".:/app:rw"
  nginx:
    depends_on:
      - marst-service
    container_name: nginx
    image: nginx:1.19-alpine
    restart: on-failure
    volumes:
      - "./:/app:ro"
      - "./docker/nginx/MarsT.conf:/etc/nginx/conf.d/app.conf:ro"
    ports:
      - 9090:9090